---
# tasks file for update_system
- name: Set Timezone
  timezone:
    name: "{{ time_zone }}"

- name: Install prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

- name: Install MC
  apt: 
    name:
      - mc
    update_cache: yes
    state: latest
