---
# tasks file for config_mysql_master

- name: Config DB Users
  import_tasks: db_users.yml

- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  tags: [ mysql ]
