---
- name: Install Prerequisites
  hosts: all
  become: yes
  roles:
  - update_system
  tags: [ update_system ]

- name: Install MySQL
  hosts: db_servers
  become: yes
  roles:
  - install_mysql
  tags: [ install_mysql ]

- name: Config DB_Servers
  hosts: db_servers
  become: yes
  roles:
  - config_mysql
  tags: [ config_mysql ]
  
- name: Config DB_Masters
  hosts: db_masters
  become: yes
  roles:
  - config_mysql_master
  tags: [ config_mysql_master ]

- name: Install ProxySQL
  hosts: proxysql
  become: yes
  roles:
  - install_proxysql
  tags: [ install_proxysql ]

- name: Config ProxySQL
  hosts: proxysql
  become: yes
  roles:
  - config_proxysql
  tags: [ config_proxysql ]


- name: Install Webserver
  hosts: webservers
  become: yes
  roles:
  - install_nginx
  - install_php
  - install_wordpress
  - config_nginx
  - config_wordpress
  - config_ssl
  tags: [ webserver ]
