---
# tasks file for config_mysql
- name: SSL assets
  import_tasks: db_certs.yml

- name: Find existing UUID if it exists
  shell: grep "^loose-group_replication_group_name" /etc/mysql/mysql.cnf | rev | cut -c -36 | rev
  run_once: true
  changed_when: false
  register: existing_cluster_uuid

- name: Generate UUID incase no previous value was present
  command: uuidgen
  run_once: true
  changed_when: false
  register: new_cluster_uuid

- name: Secure DB
  import_tasks: db_secure.yml

- name: Initial DB Config
  template:
    src: "mysql.cnf.j2"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"
  #notify: Restart MySQL

- name: Restart MySQL
  systemd: name=mysql state=restarted

- name Config Mysql Group Replication
  import_tasks: db_replica.yml
  