---
# tasks file for config_proxysql

- name: Replication Hostgroups
  proxysql_replication_hostgroups:
    login_user: admin
    login_password: admin
    writer_hostgroup: 0
    reader_hostgroup: 1
    state: present
    load_to_runtime: yes
    save_to_disk: yes 

- name: Add Backend Servers to Writer Group
  proxysql_backend_servers:
    login_user: admin
    login_password: admin
    hostname: "{{ hostvars[item].ansible_default_ipv4.address }}"
    hostgroup_id: 0
    load_to_runtime: yes
    save_to_disk: yes
    state: present
  loop: "{{ groups['db_servers'] }}"

- name: Add Backend Servers to Reader Group
  proxysql_backend_servers:
    login_user: admin
    login_password: admin
    hostname: "{{ hostvars[item].ansible_default_ipv4.address }}"
    hostgroup_id: 1
    weight: 1000
    load_to_runtime: yes
    save_to_disk: yes
    state: present
  loop: "{{ groups['db_servers'] }}"

- name: Create user for Wordpress
  import_tasks: users_config.yml

- name: Configure Monitoring
  import_tasks: monitor_config.yml

- name: Configure query rules for proxysql
  import_tasks: query_rules.yml
